### ISSUE TITLE
Hydration Warning

### ISSUE THREAD

**Issue by walleeva2018** [manjaro/website#39]
Hydration mismatch warning is given when any page is rendered 

### Reason 

In NavbarItem Theme toggle button is a client only thing but is rendering in server as well 

### Easy Fix 

Make the Theme toggle button a client only component and wrap it inside <client-only>

I can make a PR fix if this issue seems legit

**Comment by romangg** [comment]
Analysis makes sense. Where is the hidration warning being shown? In the JavaScript console?

**Comment by walleeva2018** [comment]
> Analysis makes sense. Where is the hidration warning being shown? In the JavaScript console?

Yes!!

**Comment by romangg** [comment]
Sorry for late reply. I don't see the hydration warnings in the console. Can you tell me how to replicate the issue?
