### ISSUE TITLE
Sitemap has links for not existing content pages

### ISSUE THREAD

**Issue by romangg** [manjaro/website#44]
The automatically created sitemap at https://manjaro.org/sitemap.xml since #42 contains some links to pages, that don't exist:

![Screenshot_20240814_131638](https://github.com/user-attachments/assets/423dc851-5128-4117-9cfa-d8d7d9d40539)

These are markdown files [in the content directory](https://github.com/manjaro/website/tree/master/content/products/devices) but as they are not linked and document driven mode is deactivated the pages are not generated (and also not meant to exist).

This could be a bug in the Sitemap Nuxt module.

**Comment by romangg** [comment]
@nurRiyad, do you have an idea if this is a bug in the Nuxt module or there is some configuration issue with our page?

**Comment by nurRiyad** [comment]
I will check. Give me some time. Hopefully in the next 48h

**Comment by nurRiyad** [comment]
There is a way to exclude content folder from generating sitemap. I use that and exclude the `/products/device/**` not to add in the sitemap. Fixed #45

**Comment by romangg** [comment]
Fixed by #45.
